# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askKruglov_app', '0004_auto_20161114_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
