# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askKruglov_app', '0014_remove_profile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=1000, upload_to='./static/avatars/'),
        ),
    ]
