# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('askKruglov_app', '0016_auto_20161216_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_type', models.BooleanField(default=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askKruglov_app.Answer')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askKruglov_app.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_type', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askKruglov_app.Profile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askKruglov_app.Question')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='questionlike',
            unique_together=set([('profile', 'question')]),
        ),
        migrations.AlterUniqueTogether(
            name='answerlike',
            unique_together=set([('profile', 'answer')]),
        ),
    ]
