# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askKruglov_app', '0018_remove_question_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='likes',
        ),
    ]
