# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askMe_app', '0005_auto_20161114_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='popularity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
