# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askMe_app', '0009_answer_published_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['published_time']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-published_time']},
        ),
    ]
