# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askMe_app', '0012_auto_20161116_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='', max_length=30),
        ),
    ]
