# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askMe_app', '0013_profile_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
    ]
