# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askMe_app', '0015_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/avatar.jpg', upload_to='avatars/%Y/%m/%d/%H/'),
        ),
    ]
