# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askMe_app', '0017_auto_20161216_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='likes',
        ),
    ]
